### ISSUE TITLE
Can I use one OakMapBuilder to create more than one OakMap?

### ISSUE THREAD

**Issue by fujian-zfj** [yahoo/Oak#194]
OakMapBuilder<Long, AckData> oakMapBuilder = new OakMapBuilder<>(new OakLongComparator(),
            new OakLongSerializer(), new OakAckDataSerializer(), Long.MIN_VALUE).setMemoryCapacity(MEBIBYTE);
        for (int i = 0; i < 1000; i ++) {
            OakMap<Long, AckData> oakMap = oakMapBuilder.buildOrderedMap();
        }
![image](https://user-images.githubusercontent.com/10379042/147430556-74b4c3fc-0285-443e-b910-a67f067b7c1e.png)

And If I use one OakMapBuilder to create more than one OakMap in multi-threaded process, NativeMemoryAllocator will be Instantiated multiple times.

**Comment by liran-funaro** [comment]
Thanks for finding this issue. PR #196 addresses this issue.
