### ISSUE TITLE
Enforce setting of serializer and comparator

### ISSUE THREAD

**Issue by ohad7** [yahoo/Oak#63]
Would be great if you can add a check whether the comparator is null to the OakBuilder.build() method - it's stated in the documentation, but still good to have it to save developer time

**Comment by sanastas** [comment]
I will change OakMapBuilder constructor to request comparator and serializer as input.

**Comment by sanastas** [comment]
The change was done. Closing the issue.

**Comment by sanastas** [comment]
The change was done. Closing the issue.
